### ISSUE TITLE
_getMissingFieldsInConfiguration

### ISSUE THREAD

**Issue by noojijs** [Viber/viber-bot-node#2]
the parameters are reversed. 

should be

ViberBot.prototype._getMissingFieldsInConfiguration = function(configuration) {
  return _.difference(REQUIRED_CONFIGURATION_FIELDS, Object.keys(configuration));
};

**Comment by idanh** [comment]
Hi @noojijs ,
Thank you for noticing. This will be fixed on next release.

**Comment by idanh** [comment]
Added missing tests: https://github.com/Viber/viber-bot-node/commit/d2b4dec4912556dc13f147b2765b0e96c1502dd7

**Comment by prodigic** [comment]
Thanks. Noticed it as I was wiring in the "/post" endpoint to my fork. Needed to provide an admin user to allow the bot to post to the PA
